module.exports={
    devServer:{
        proxy:{
            '/aqi':{
                target:'https://opendata.epa.gov.tw',
                changeOrigin:true,
                ws:true,
                pathRewrite:{
                    '^/aqi':''
                }
            }
        }
    }
}